### ISSUE TITLE
This is not needed

### ISSUE THREAD

**Issue by aradalvand** [sqids/sqids-f-sharp#1]
@4kimov Hi there.

F# is a .NET language, and [`sqids-dotnet`](https://github.com/sqids/sqids-dotnet) is [CLS-compliant](https://learn.microsoft.com/en-us/dotnet/standard/language-independence), meaning that any .NET language could use it, including F#, so we don't need a separate F# implementation, [`sqids-dotnet`](https://github.com/sqids/sqids-dotnet) already supports F#.

So, feel free to delete this repo, and also remove F# from the "Languages" list on the website.

---

I also tested it and confirmed that it works — the steps:
- Run `dotnet new console -lang 'F#'`
- Run `dotnet add package Sqids`
- Put this in `Program.fs`:
```fsharp
open Sqids;

let sqids = SqidsEncoder<int>()
let id = sqids.Encode 1
let numbers = sqids.Decode id
printfn "ID: %s" id
printfn "Numbers: %d" numbers.Count
```
- Run the program with `dotnet run`
- It runs and you get the expected output:
![image](https://github.com/sqids/sqids-f-sharp/assets/26527405/40a23b62-1025-41ee-a73b-7d86f4ad5019)

**Comment by 4kimov** [comment]
Thanks for the heads up + testing. I'll remove.
